Skip to content
Search or jump to…
Pull requests
Issues
Codespaces
Marketplace
Explore
 
@ShafiyaHeenaCen 
ShafiyaHeenaCen
/
comp367_project
Public
Code
Issues
4
Pull requests
2
Actions
Projects
Wiki
Security
Insights
Settings
comp367_project/azure-pipelines-1.yml
@ShafiyaHeenaCen
ShafiyaHeenaCen Update azure-pipelines-1.yml
Latest commit 6edb999 19 minutes ago
 History
 1 contributor
38 lines (31 sloc)  696 Bytes

# Test commit

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        command: 'push'
        
    - bash: echo "This is test stage"
      displayName: Test stage

- stage: Deliver
  displayName: ContinousDeploy
  jobs:
  - job: Dev Deploy
    displayName: Deploy to Dev Env
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: echo "Deploying to Development Environment"
      displayName: Dev Deploy

  - job: QAT Deploy
    displayName: Deploy to QAT Env
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: echo "Deploying to QAT Environment"
      displayName: QAT Deploy

  - job: Staging Deploy
    displayName: Deploy to Staging Env
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: echo "Deploying to Staging Environment"
      displayName: Staging Deploy

  - job: Production Deploy
    displayName: Deploy to Production Env
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: echo "Deploying to Production Environment"
      displayName: Production Deploy
